#!/usr/bin/env python3
"""Regenerate every utility-algo JSON under a run root using the current code.

Use this after a behavioral change to the utility prompt pipeline (e.g. the
iter-0 policy_guidance fix on branch iter0-no-policy-guidance). For each
existing utility run, the script reads meta to reconstruct the exact CLI
invocation, invokes run_algorithm.py, and on success deletes the old file.

Defaults to --dry-run. Pass --execute to actually launch the work.

Examples:
    # Preview the work
    python scripts/regenerate_utility_runs.py \
        --root outputs/paper__REPS40__iters25__seed1234__20260511_163727

    # Regenerate, 4 concurrent jobs per API lane
    python scripts/regenerate_utility_runs.py \
        --root outputs/paper__REPS40__iters25__seed1234__20260511_163727 \
        --execute --jobs 4

    # Just one scenario / one API
    python scripts/regenerate_utility_runs.py \
        --root outputs/paper__REPS40__iters25__seed1234__20260511_163727 \
        --scenario flights_chi_nyc --api groq --execute
"""
from __future__ import annotations

import argparse
import concurrent.futures as cf
import json
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

REPO_ROOT = Path(__file__).resolve().parents[1]
RUN_ALGO = REPO_ROOT / "run_algorithm.py"


@dataclass
class Job:
    old_file: Path
    scenario: str
    mode: str
    api_model: str
    seed: int
    iterations: int
    batch_size: Optional[int]
    section_order: Optional[List[str]]
    utility_prompt_strategy: Optional[str]
    utility_prompt_variant: Optional[str]
    run_stamp: str
    output_root: Path

    def cli_args(self) -> List[str]:
        args = [
            sys.executable,
            str(RUN_ALGO),
            "--algo", "utility",
            "--scenario", self.scenario,
            "--mode", self.mode,
            "--api-model", self.api_model,
            "--iterations", str(self.iterations),
            "--seed", str(self.seed),
            "--output-root", str(self.output_root),
            "--run-stamp", self.run_stamp,
        ]
        if self.batch_size is not None:
            args += ["--batch-size", str(self.batch_size)]
        if self.utility_prompt_strategy:
            args += ["--utility-prompt-strategy", self.utility_prompt_strategy]
        if self.utility_prompt_variant:
            args += ["--utility-prompt-variant", self.utility_prompt_variant]
        if self.section_order:
            args += ["--section-order", ",".join(self.section_order)]
        return args


def load_job(path: Path, current_git_hash: Optional[str]) -> Optional[Job]:
    """Return a Job for `path`, or None if it should be skipped."""
    try:
        payload = json.loads(path.read_text())
    except Exception as exc:
        print(f"[SKIP] {path.name}: unreadable ({exc})", file=sys.stderr)
        return None

    meta = payload.get("meta") or {}
    if meta.get("algo") != "utility":
        return None

    cfg = meta.get("config") or {}
    section_order = cfg.get("section_order")
    if section_order and "priorities" not in [s.lower() for s in section_order]:
        # Fix doesn't change these — iter-0 already excluded priorities.
        return None
    if not section_order:
        # Legacy runs without section_order rely on scenario_header, which the
        # fix doesn't touch either.
        return None

    # Skip runs whose mode has an empty policy_guidance (e.g. BASE). The old
    # buggy code injected this string as the "priorities" section at iter 0,
    # but the empty-section filter (`if (sections.get(name) or "").strip()`)
    # already hid empty strings — so iter 0 was unchanged. Re-running these
    # produces statistically-equivalent but not byte-identical LLM output and
    # wastes API calls.
    mode_name = meta.get("mode")
    modes = cfg.get("modes") or {}
    mode_def = modes.get(mode_name) or {}
    policy_guidance = (mode_def.get("prompt") or mode_def.get("utility_prompt_text") or "")
    if not str(policy_guidance).strip():
        return None

    if current_git_hash:
        git_meta = meta.get("git") or {}
        if git_meta.get("git_hash") == current_git_hash:
            # git_hash match is sufficient — the iter-0 fix is in HEAD, so the
            # file was generated by the patched code path. We intentionally do
            # not gate on git_dirty: the working tree often has unrelated plot
            # / docs edits, and re-running 2400+ utility experiments for
            # cosmetic dirt would waste API budget.
            return None

    output_root = path.parent

    return Job(
        old_file=path,
        scenario=meta["scenario"],
        mode=meta["mode"],
        api_model=meta["api_model"],
        seed=int(meta["seed"]),
        iterations=int(meta["max_iters"]),
        batch_size=int(meta["batch_size"]) if meta.get("batch_size") is not None else None,
        section_order=list(section_order) if section_order else None,
        utility_prompt_strategy=cfg.get("utility_prompt_strategy_override"),
        utility_prompt_variant=cfg.get("utility_prompt_variant_override"),
        run_stamp=path.stem.split("__")[-1],
        output_root=output_root,
    )


def discover_jobs(root: Path,
                  scenario_filter: Optional[str],
                  api_filter: Optional[str],
                  current_git_hash: Optional[str]) -> List[Job]:
    jobs: List[Job] = []
    scenario_dirs = sorted(p for p in root.iterdir() if p.is_dir())
    for scen_dir in scenario_dirs:
        if scenario_filter and scen_dir.name != scenario_filter:
            continue
        for json_path in sorted(scen_dir.glob("*__utility__*.json")):
            job = load_job(json_path, current_git_hash)
            if job is None:
                continue
            if api_filter and job.api_model != api_filter:
                continue
            jobs.append(job)
    return jobs


def run_one(job: Job, keep_old: bool) -> tuple[Job, bool, str]:
    """Run a single regeneration. Returns (job, success, stderr_tail)."""
    cmd = job.cli_args()
    # Snapshot directory contents before so we can identify the new file even
    # if its filename diverges from the old one (e.g. _build_filename_settings
    # adds suffix tokens that weren't present in older runs).
    pre = set(job.output_root.glob("*.json"))
    try:
        proc = subprocess.run(
            cmd, cwd=REPO_ROOT, check=False,
            capture_output=True, text=True,
        )
    except Exception as exc:
        return job, False, f"subprocess raised: {exc}"

    if proc.returncode != 0:
        tail = (proc.stderr or proc.stdout or "")[-2000:]
        return job, False, tail

    post = set(job.output_root.glob("*.json"))
    new_files = [p for p in (post - pre) if p != job.old_file]
    if not new_files:
        return job, False, "run_algorithm.py exited 0 but produced no new JSON"

    if not keep_old and job.old_file.exists() and job.old_file not in new_files:
        try:
            job.old_file.unlink()
        except OSError as exc:
            return job, True, f"new file written but old removal failed: {exc}"

    return job, True, ""


def current_git_hash() -> Optional[str]:
    try:
        out = subprocess.check_output(
            ["git", "-C", str(REPO_ROOT), "rev-parse", "HEAD"],
            stderr=subprocess.DEVNULL,
        ).decode().strip()
        return out or None
    except Exception:
        return None


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", type=Path, required=True,
                    help="Run root containing per-scenario subfolders.")
    ap.add_argument("--scenario", help="Restrict to one scenario folder.")
    ap.add_argument("--api", choices=["groq", "gemini"],
                    help="Restrict to one api_model.")
    ap.add_argument("--jobs", type=int, default=1,
                    help="Concurrent run_algorithm.py invocations per API lane (default 1).")
    ap.add_argument("--execute", action="store_true",
                    help="Actually run the regeneration. Default is dry-run.")
    ap.add_argument("--keep-old", action="store_true",
                    help="Keep the old JSON files instead of deleting after a successful regeneration.")
    ap.add_argument("--limit", type=int,
                    help="Run at most N jobs (for smoke-testing).")
    ap.add_argument("--ignore-git-hash", action="store_true",
                    help="Re-run files even if their meta.git.git_hash already matches HEAD.")
    return ap.parse_args()


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    if not root.is_dir():
        print(f"[ERR] not a directory: {root}", file=sys.stderr)
        return 2

    git_hash = None if args.ignore_git_hash else current_git_hash()
    if git_hash:
        print(f"[INFO] HEAD: {git_hash} (files already at this hash are skipped)")

    jobs = discover_jobs(root, args.scenario, args.api, git_hash)
    if args.limit:
        jobs = jobs[: args.limit]

    if not jobs:
        print("[INFO] No utility runs need regeneration.")
        return 0

    # Summarize plan
    by_api: dict[str, int] = {}
    by_scen: dict[str, int] = {}
    for j in jobs:
        by_api[j.api_model] = by_api.get(j.api_model, 0) + 1
        by_scen[j.scenario] = by_scen.get(j.scenario, 0) + 1
    print(f"[PLAN] {len(jobs)} utility runs to regenerate")
    print("  per scenario:", ", ".join(f"{k}={v}" for k, v in sorted(by_scen.items())))
    print("  per api    :", ", ".join(f"{k}={v}" for k, v in sorted(by_api.items())))

    if not args.execute:
        print("\n[DRY-RUN] First 3 sample commands:")
        for j in jobs[:3]:
            print("  $", " ".join(j.cli_args()))
        print("\nRe-run with --execute to apply.")
        return 0

    # Split jobs into per-API lanes so groq/gemini run concurrently while each
    # respects its own rate limit. Within a lane: --jobs workers.
    lanes: dict[str, list[Job]] = {}
    for j in jobs:
        lanes.setdefault(j.api_model, []).append(j)

    succeeded = 0
    failed: list[tuple[Job, str]] = []

    def lane_worker(api: str, lane_jobs: list[Job]) -> None:
        nonlocal succeeded
        with cf.ThreadPoolExecutor(max_workers=args.jobs) as pool:
            futures = {pool.submit(run_one, j, args.keep_old): j for j in lane_jobs}
            for fut in cf.as_completed(futures):
                job, ok, msg = fut.result()
                tag = f"{job.api_model}/{job.scenario}/{job.mode}/seed{job.seed}"
                if ok:
                    succeeded += 1
                    print(f"[OK  ] {tag}{(' — ' + msg) if msg else ''}")
                else:
                    failed.append((job, msg))
                    print(f"[FAIL] {tag}: {msg.splitlines()[-1] if msg else 'unknown'}",
                          file=sys.stderr)

    with cf.ThreadPoolExecutor(max_workers=len(lanes)) as outer:
        outer.map(lambda kv: lane_worker(*kv), lanes.items())

    total = len(jobs)
    print(f"\n[DONE] {succeeded}/{total} succeeded, {len(failed)} failed")
    if failed:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
